---
env:
  es2020: true
parserOptions:
  project: ./tsconfig.json
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - prettier
